### ISSUE TITLE
Less secure app access

### ISSUE THREAD

**Issue by phamduyphat** [GamehunterKaan/BadUSB-Browser#10]
As of May 30th, 2022, less secure app access has been disabled.

I suggest using webhook or sth as a method of transfering multiple jsons

**Comment by ghost** [comment]
> As of May 30th, 2022, less secure app access has been disabled.
> 
> I suggest using webhook or sth as a method of transfering multiple jsons

so, i recoment you use the smtp microsoft server, its free has a tutorial on web how do you do this
