### ISSUE TITLE
Caps Lock problem

### ISSUE THREAD

**Issue by AllCheeks** [GamehunterKaan/BadUSB-Browser#3]
How can I keep him in lowercase
uppercase commands cannot be run

example:
Keyboard.print("hello");
But the output Notepad becomes
HELLO

**Comment by GamehunterKaan** [comment]
Are you using arduino?

**Comment by AllCheeks** [comment]
yes

**Comment by GamehunterKaan** [comment]
I've never used Arduino as a Bad USB and this issue is also not related with my code.
