### ISSUE TITLE
Inquiring about other adresses than gmail, would they work?

### ISSUE THREAD

**Issue by minuspal** [GamehunterKaan/BadUSB-Browser#6]
Hello, sorry for the inquiry however, would this script support other email adresses than @gmail.com ? something like @protonmail.com would be awesome. And would there be any solution to use a discord webhook to send the results via discord instead of gmail? Thanks :)

**Comment by GamehunterKaan** [comment]
I haven't tested it but I'm pretty sure it would support protonmail, but i am not sure about discord webhook. It might be possible using [this project.](https://github.com/EvotecIT/PSDiscord)

**Comment by minuspal** [comment]
> I haven't tested it but I'm pretty sure it would support protonmail, but i am not sure about discord webhook. It might be possible using [this project.](https://github.com/EvotecIT/PSDiscord)

Thanks, if you get to it please try protonmail :) also I heard that this script needs to be modified to work on the pico, right? Correct me if I'm wrong but if so what changes are needed? Thanks again :)

**Comment by GamehunterKaan** [comment]
> also I heard that this script needs to be modified to work on the pico, right?

I also use Pico too, all you have to do is rename inject.txt to payload.dd and you should be good to go!
