### ISSUE TITLE
Where do I find the payload?

### ISSUE THREAD

**Issue by nthacker69** [GamehunterKaan/BadUSB-Browser#8]
No browser can download the hackbrowser.exe (even tor) so I have absolutely no idea how to get the payload.

**Comment by GamehunterKaan** [comment]
No need to download the `hackbrowser.exe` using a browser. All you have to do is fork this repo, change the fields I've marked in the [payload.ps1](https://github.com/GamehunterKaan/BadUSB-Browser/blob/main/payload.ps1) and [inject.txt](https://github.com/GamehunterKaan/BadUSB-Browser/blob/main/inject.txt) files, and then you should be good to go!
